# This file was generated by Restikle: http://github.com/tillless/restikle
schema "20150111075238" do
  entity "FriendlyIdSlug" do
    integer64  :id, default: -1
    string     :slug, null: false
    integer64  :sluggable_id, null: false
    string     :sluggable_type, limit: 50
    string     :scope
    datetime   :created_at
  end
  entity "Address" do
    integer64  :id, default: -1
    string     :firstname
    string     :lastname
    string     :address1
    string     :address2
    string     :city
    string     :zipcode
    string     :phone
    string     :state_name
    string     :alternative_phone
    string     :company
    integer64  :state_id
    integer64  :country_id
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Adjustment" do
    integer64  :id, default: -1
    integer64  :source_id
    string     :source_type
    integer64  :adjustable_id
    string     :adjustable_type
    decimal    :amount, precision: 10, scale: 2
    string     :label
    boolean    :mandatory
    boolean    :eligible, default: true
    datetime   :created_at
    datetime   :updated_at
    string     :state
    integer64  :order_id
    boolean    :included, default: false
  end
  entity "Asset" do
    integer64  :id, default: -1
    integer64  :viewable_id
    string     :viewable_type
    integer64  :attachment_width
    integer64  :attachment_height
    integer64  :attachment_file_size
    integer64  :position
    string     :attachment_content_type
    string     :attachment_file_name
    string     :type, limit: 75
    datetime   :attachment_updated_at
    string     :alt
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Calculator" do
    integer64  :id, default: -1
    string     :type
    integer64  :calculable_id
    string     :calculable_type
    datetime   :created_at
    datetime   :updated_at
    string     :preferences
  end
  entity "Configuration" do
    integer64  :id, default: -1
    string     :name
    string     :type, limit: 50
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Country" do
    integer64  :id, default: -1
    string     :iso_name
    string     :iso
    string     :iso3
    string     :name
    integer64  :numcode
    boolean    :states_required, default: false
    datetime   :updated_at
    has_many   :states                # MANUAL
  end
  entity "CreditCard" do
    integer64  :id, default: -1
    string     :month
    string     :year
    string     :cc_type
    string     :last_digits
    integer64  :address_id
    string     :gateway_customer_profile_id
    string     :gateway_payment_profile_id
    datetime   :created_at
    datetime   :updated_at
    string     :name
    integer64  :user_id
    integer64  :payment_method_id
    boolean    :default, default: false, null: false
  end
  entity "CustomerReturn" do
    integer64  :id, default: -1
    string     :number
    integer64  :stock_location_id
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Gateway" do
    integer64  :id, default: -1
    string     :type
    string     :name
    string     :descrip
    boolean    :active, default: true
    string     :environment, default: "development"
    string     :server, default: "test"
    boolean    :test_mode, default: true
    datetime   :created_at
    datetime   :updated_at
    string     :preferences
  end
  entity "InventoryUnit" do
    integer64  :id, default: -1
    string     :state
    integer64  :variant_id
    integer64  :order_id
    integer64  :shipment_id
    datetime   :created_at
    datetime   :updated_at
    boolean    :pending, default: true
    integer64  :line_item_id
  end
  entity "LineItem" do
    integer64  :id, default: -1
    integer64  :variant_id
    integer64  :order_id
    integer64  :quantity, null: false
    decimal    :price, precision: 10, scale: 2, null: false
    datetime   :created_at
    datetime   :updated_at
    string     :currency
    decimal    :cost_price, precision: 10, scale: 2
    integer64  :tax_category_id
    decimal    :adjustment_total, precision: 10, scale: 2, default: 0.0
    decimal    :additional_tax_total, precision: 10, scale: 2, default: 0.0
    decimal    :promo_total, precision: 10, scale: 2, default: 0.0
    decimal    :included_tax_total, precision: 10, scale: 2, default: 0.0, null: false
    decimal    :pre_tax_amount, precision: 8, scale: 2, default: 0.0
  end
  entity "LogEntry" do
    integer64  :id, default: -1
    integer64  :source_id
    string     :source_type
    string     :details
    datetime   :created_at
    datetime   :updated_at
  end
  entity "OptionType" do
    integer64  :id, default: -1
    string     :name, limit: 100
    string     :presentation, limit: 100
    integer64  :position, default: 0, null: false
    datetime   :created_at
    datetime   :updated_at
  end
  entity "OptionTypesPrototype" do
    integer64  :id, default: -1
    integer64  :prototype_id
    integer64  :option_type_id
  end
  entity "OptionValue" do
    integer64  :id, default: -1
    integer64  :position
    string     :name
    string     :presentation
    integer64  :option_type_id
    datetime   :created_at
    datetime   :updated_at
  end
  entity "OptionValuesVariant" do
    integer64  :id, default: -1
    integer64  :variant_id
    integer64  :option_value_id
  end
  entity "Order" do
    integer64  :id, default: -1
    string     :number, limit: 32
    decimal    :item_total, precision: 10, scale: 2, default: 0.0, null: false
    decimal    :total, precision: 10, scale: 2, default: 0.0, null: false
    string     :state
    decimal    :adjustment_total, precision: 10, scale: 2, default: 0.0, null: false
    integer64  :user_id
    datetime   :completed_at
    integer64  :bill_address_id
    integer64  :ship_address_id
    decimal    :payment_total, precision: 10, scale: 2, default: 0.0
    integer64  :shipping_method_id
    string     :shipment_state
    string     :payment_state
    string     :email
    string     :special_instructions
    datetime   :created_at
    datetime   :updated_at
    string     :currency
    string     :last_ip_address
    integer64  :created_by_id
    decimal    :shipment_total, precision: 10, scale: 2, default: 0.0, null: false
    decimal    :additional_tax_total, precision: 10, scale: 2, default: 0.0
    decimal    :promo_total, precision: 10, scale: 2, default: 0.0
    string     :channel, default: "spree"
    decimal    :included_tax_total, precision: 10, scale: 2, default: 0.0, null: false
    integer64  :item_count, default: 0
    integer64  :approver_id
    datetime   :approved_at
    boolean    :confirmation_delivered, default: false
    boolean    :considered_risky, default: false
    string     :guest_token
    datetime   :canceled_at
    integer64  :canceler_id
    integer64  :store_id
    integer64  :state_lock_version, default: 0, null: false
  end
  entity "OrdersPromotion" do
    integer64  :id, default: -1
    integer64  :order_id
    integer64  :promotion_id
  end
  entity "PaymentCaptureEvent" do
    integer64  :id, default: -1
    decimal    :amount, precision: 10, scale: 2, default: 0.0
    integer64  :payment_id
    datetime   :created_at
    datetime   :updated_at
  end
  entity "PaymentMethod" do
    integer64  :id, default: -1
    string     :type
    string     :name
    string     :descrip
    boolean    :active, default: true
    string     :environment, default: "development"
    datetime   :deleted_at
    datetime   :created_at
    datetime   :updated_at
    string     :display_on
    boolean    :auto_capture
    string     :preferences
  end
  entity "Payment" do
    integer64  :id, default: -1
    decimal    :amount, precision: 10, scale: 2, default: 0.0, null: false
    integer64  :order_id
    integer64  :source_id
    string     :source_type
    integer64  :payment_method_id
    string     :state
    string     :response_code
    string     :avs_response
    datetime   :created_at
    datetime   :updated_at
    string     :identifier
    string     :cvv_response_code
    string     :cvv_response_message
  end
  entity "Preference" do
    integer64  :id, default: -1
    string     :value
    string     :key
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Price" do
    integer64  :id, default: -1
    integer64  :variant_id, null: false
    decimal    :amount, precision: 10, scale: 2
    string     :currency
    datetime   :deleted_at
  end
  entity "ProductOptionType" do
    integer64  :id, default: -1
    integer64  :position
    integer64  :product_id
    integer64  :option_type_id
    datetime   :created_at
    datetime   :updated_at
  end
  entity "ProductProperty" do
    integer64  :id, default: -1
    string     :value
    integer64  :product_id
    integer64  :property_id
    datetime   :created_at
    datetime   :updated_at
    integer64  :position, default: 0
  end
  entity "Product" do
    integer64  :id, default: -1
    string     :name, default: "", null: false
    string     :descrip
    datetime   :available_on
    datetime   :deleted_at
    string     :slug
    string     :meta_descrip
    string     :meta_keywords
    integer64  :tax_category_id
    integer64  :shipping_category_id
    datetime   :created_at
    datetime   :updated_at
    boolean    :promotionable, default: true
    string     :meta_title
  end
  entity "ProductsPromotionRule" do
    integer64  :id, default: -1
    integer64  :product_id
    integer64  :promotion_rule_id
  end
  entity "ProductsTaxon" do
    integer64  :id, default: -1
    integer64  :product_id
    integer64  :taxon_id
    integer64  :position
  end
  entity "PromotionActionLineItem" do
    integer64  :id, default: -1
    integer64  :promotion_action_id
    integer64  :variant_id
    integer64  :quantity, default: 1
  end
  entity "PromotionAction" do
    integer64  :id, default: -1
    integer64  :promotion_id
    integer64  :position
    string     :type
    datetime   :deleted_at
  end
  entity "PromotionCategory" do
    integer64  :id, default: -1
    string     :name
    datetime   :created_at
    datetime   :updated_at
  end
  entity "PromotionRule" do
    integer64  :id, default: -1
    integer64  :promotion_id
    integer64  :user_id
    integer64  :product_group_id
    string     :type
    datetime   :created_at
    datetime   :updated_at
    string     :code
    string     :preferences
  end
  entity "PromotionRulesUser" do
    integer64  :id, default: -1
    integer64  :user_id
    integer64  :promotion_rule_id
  end
  entity "Promotion" do
    integer64  :id, default: -1
    string     :descrip
    datetime   :expires_at
    datetime   :starts_at
    string     :name
    string     :type
    integer64  :usage_limit
    string     :match_policy, default: "all"
    string     :code
    boolean    :advertise, default: false
    string     :path
    datetime   :created_at
    datetime   :updated_at
    integer64  :promotion_category_id
  end
  entity "Property" do
    integer64  :id, default: -1
    string     :name
    string     :presentation, null: false
    datetime   :created_at
    datetime   :updated_at
  end
  entity "PropertiesPrototype" do
    integer64  :id, default: -1
    integer64  :prototype_id
    integer64  :property_id
  end
  entity "Prototype" do
    integer64  :id, default: -1
    string     :name
    datetime   :created_at
    datetime   :updated_at
  end
  entity "RefundReason" do
    integer64  :id, default: -1
    string     :name
    boolean    :active, default: true
    boolean    :mutable, default: true
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Refund" do
    integer64  :id, default: -1
    integer64  :payment_id
    decimal    :amount, precision: 10, scale: 2, default: 0.0, null: false
    string     :transaction_id
    datetime   :created_at
    datetime   :updated_at
    integer64  :refund_reason_id
    integer64  :reimbursement_id
  end
  entity "ReimbursementCredit" do
    integer64  :id, default: -1
    decimal    :amount, precision: 10, scale: 2, default: 0.0, null: false
    integer64  :reimbursement_id
    integer64  :creditable_id
    string     :creditable_type
  end
  entity "ReimbursementType" do
    integer64  :id, default: -1
    string     :name
    boolean    :active, default: true
    boolean    :mutable, default: true
    datetime   :created_at
    datetime   :updated_at
    string     :type
  end
  entity "Reimbursement" do
    integer64  :id, default: -1
    string     :number
    string     :reimbursement_status
    integer64  :customer_return_id
    integer64  :order_id
    decimal    :total, precision: 10, scale: 2
    datetime   :created_at
    datetime   :updated_at
  end
  entity "ReturnAuthorizationReason" do
    integer64  :id, default: -1
    string     :name
    boolean    :active, default: true
    boolean    :mutable, default: true
    datetime   :created_at
    datetime   :updated_at
  end
  entity "ReturnAuthorization" do
    integer64  :id, default: -1
    string     :number
    string     :state
    integer64  :order_id
    string     :memo
    datetime   :created_at
    datetime   :updated_at
    integer64  :stock_location_id
    integer64  :return_authorization_reason_id
  end
  entity "ReturnItem" do
    integer64  :id, default: -1
    integer64  :return_authorization_id
    integer64  :inventory_unit_id
    integer64  :exchange_variant_id
    datetime   :created_at
    datetime   :updated_at
    decimal    :pre_tax_amount, precision: 12, scale: 4, default: 0.0, null: false
    decimal    :included_tax_total, precision: 12, scale: 4, default: 0.0, null: false
    decimal    :additional_tax_total, precision: 12, scale: 4, default: 0.0, null: false
    string     :reception_status
    string     :acceptance_status
    integer64  :customer_return_id
    integer64  :reimbursement_id
    integer64  :exchange_inventory_unit_id
    string     :acceptance_status_errors
    integer64  :preferred_reimbursement_type_id
    integer64  :override_reimbursement_type_id
  end
  entity "Role" do
    integer64  :id, default: -1
    string     :name
  end
  entity "RolesUser" do
    integer64  :id, default: -1
    integer64  :role_id
    integer64  :user_id
  end
  entity "Shipment" do
    integer64  :id, default: -1
    string     :tracking
    string     :number
    decimal    :cost, precision: 10, scale: 2, default: 0.0
    datetime   :shipped_at
    integer64  :order_id
    integer64  :address_id
    string     :state
    datetime   :created_at
    datetime   :updated_at
    integer64  :stock_location_id
    decimal    :adjustment_total, precision: 10, scale: 2, default: 0.0
    decimal    :additional_tax_total, precision: 10, scale: 2, default: 0.0
    decimal    :promo_total, precision: 10, scale: 2, default: 0.0
    decimal    :included_tax_total, precision: 10, scale: 2, default: 0.0, null: false
    decimal    :pre_tax_amount, precision: 8, scale: 2, default: 0.0
  end
  entity "ShippingCategory" do
    integer64  :id, default: -1
    string     :name
    datetime   :created_at
    datetime   :updated_at
  end
  entity "ShippingMethodCategory" do
    integer64  :id, default: -1
    integer64  :shipping_method_id, null: false
    integer64  :shipping_category_id, null: false
    datetime   :created_at
    datetime   :updated_at
  end
  entity "ShippingMethod" do
    integer64  :id, default: -1
    string     :name
    string     :display_on
    datetime   :deleted_at
    datetime   :created_at
    datetime   :updated_at
    string     :tracking_url
    string     :admin_name
    integer64  :tax_category_id
    string     :code
  end
  entity "ShippingMethodsZone" do
    integer64  :id, default: -1
    integer64  :shipping_method_id
    integer64  :zone_id
  end
  entity "ShippingRate" do
    integer64  :id, default: -1
    integer64  :shipment_id
    integer64  :shipping_method_id
    boolean    :selected, default: false
    decimal    :cost, precision: 8, scale: 2, default: 0.0
    datetime   :created_at
    datetime   :updated_at
    integer64  :tax_rate_id
  end
  entity "SkrillTransaction" do
    integer64  :id, default: -1
    string     :email
    float      :amount
    string     :currency
    integer64  :transaction_id
    integer64  :customer_id
    string     :payment_type
    datetime   :created_at
    datetime   :updated_at
  end
  entity "StateChange" do
    integer64  :id, default: -1
    string     :name
    string     :previous_state
    integer64  :stateful_id
    integer64  :user_id
    string     :stateful_type
    string     :next_state
    datetime   :created_at
    datetime   :updated_at
  end
  entity "State" do
    integer64  :id, default: -1
    string     :name
    string     :abbr
    integer64  :country_id
    datetime   :updated_at
    belongs_to :country                 # MANUAL
  end
  entity "StockItem" do
    integer64  :id, default: -1
    integer64  :stock_location_id
    integer64  :variant_id
    integer64  :count_on_hand, default: 0, null: false
    datetime   :created_at
    datetime   :updated_at
    boolean    :backorderable, default: false
    datetime   :deleted_at
  end
  entity "StockLocation" do
    integer64  :id, default: -1
    string     :name
    datetime   :created_at
    datetime   :updated_at
    boolean    :default, default: false, null: false
    string     :address1
    string     :address2
    string     :city
    integer64  :state_id
    string     :state_name
    integer64  :country_id
    string     :zipcode
    string     :phone
    boolean    :active, default: true
    boolean    :backorderable_default, default: false
    boolean    :propagate_all_variants, default: true
    string     :admin_name
  end
  entity "StockMovement" do
    integer64  :id, default: -1
    integer64  :stock_item_id
    integer64  :quantity, default: 0
    string     :action
    datetime   :created_at
    datetime   :updated_at
    integer64  :originator_id
    string     :originator_type
  end
  entity "StockTransfer" do
    integer64  :id, default: -1
    string     :type
    string     :reference
    integer64  :source_location_id
    integer64  :destination_location_id
    datetime   :created_at
    datetime   :updated_at
    string     :number
  end
  entity "Store" do
    integer64  :id, default: -1
    string     :name
    string     :url
    string     :meta_descrip
    string     :meta_keywords
    string     :seo_title
    string     :mail_from_address
    string     :default_currency
    string     :code
    boolean    :default, default: false, null: false
    datetime   :created_at
    datetime   :updated_at
  end
  entity "TaxCategory" do
    integer64  :id, default: -1
    string     :name
    string     :descrip
    boolean    :is_default, default: false
    datetime   :deleted_at
    datetime   :created_at
    datetime   :updated_at
    string     :tax_code
  end
  entity "TaxRate" do
    integer64  :id, default: -1
    decimal    :amount, precision: 8, scale: 5
    integer64  :zone_id
    integer64  :tax_category_id
    boolean    :included_in_price, default: false
    datetime   :created_at
    datetime   :updated_at
    string     :name
    boolean    :show_rate_in_label, default: true
    datetime   :deleted_at
  end
  entity "Taxonomy" do
    integer64  :id, default: -1
    string     :name, null: false
    datetime   :created_at
    datetime   :updated_at
    integer64  :position, default: 0
  end
  entity "Taxon" do
    integer64  :id, default: -1
    integer64  :parent_id
    integer64  :position, default: 0
    string     :name, null: false
    string     :permalink
    integer64  :taxonomy_id
    integer64  :lft
    integer64  :rgt
    string     :icon_file_name
    string     :icon_content_type
    integer64  :icon_file_size
    datetime   :icon_updated_at
    string     :descrip
    datetime   :created_at
    datetime   :updated_at
    string     :meta_title
    string     :meta_descrip
    string     :meta_keywords
    integer64  :depth
  end
  entity "TaxonsPromotionRule" do
    integer64  :id, default: -1
    integer64  :taxon_id
    integer64  :promotion_rule_id
  end
  entity "TaxonsPrototype" do
    integer64  :id, default: -1
    integer64  :taxon_id
    integer64  :prototype_id
  end
  entity "TokenizedPermission" do
    integer64  :id, default: -1
    integer64  :permissable_id
    string     :permissable_type
    string     :token
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Tracker" do
    integer64  :id, default: -1
    string     :environment
    string     :analytics_id
    boolean    :active, default: true
    datetime   :created_at
    datetime   :updated_at
  end
  entity "User" do
    integer64  :id, default: -1
    string     :encrypted_password, limit: 128
    string     :password_salt, limit: 128
    string     :email
    string     :remember_token
    string     :persistence_token
    string     :reset_password_token
    string     :perishable_token
    integer64  :sign_in_count, default: 0, null: false
    integer64  :failed_attempts, default: 0, null: false
    datetime   :last_request_at
    datetime   :current_sign_in_at
    datetime   :last_sign_in_at
    string     :current_sign_in_ip
    string     :last_sign_in_ip
    string     :login
    integer64  :ship_address_id
    integer64  :bill_address_id
    string     :authentication_token
    string     :unlock_token
    datetime   :locked_at
    datetime   :reset_password_sent_at
    datetime   :created_at
    datetime   :updated_at
    string     :spree_api_key, limit: 48
    datetime   :remember_created_at
    datetime   :deleted_at
    string     :confirmation_token
    datetime   :confirmed_at
    datetime   :confirmation_sent_at
  end
  entity "Variant" do
    integer64  :id, default: -1
    string     :sku, default: "", null: false
    decimal    :weight, precision: 8, scale: 2, default: 0.0
    decimal    :height, precision: 8, scale: 2
    decimal    :width, precision: 8, scale: 2
    decimal    :depth, precision: 8, scale: 2
    datetime   :deleted_at
    boolean    :is_master, default: false
    integer64  :product_id
    decimal    :cost_price, precision: 10, scale: 2
    integer64  :position
    string     :cost_currency
    boolean    :track_inventory, default: true
    integer64  :tax_category_id
    datetime   :updated_at
    integer64  :stock_items_count, default: 0, null: false
  end
  entity "ZoneMember" do
    integer64  :id, default: -1
    integer64  :zoneable_id
    string     :zoneable_type
    integer64  :zone_id
    datetime   :created_at
    datetime   :updated_at
  end
  entity "Zone" do
    integer64  :id, default: -1
    string     :name
    string     :descrip
    boolean    :default_tax, default: false
    integer64  :zone_members_count, default: 0
    datetime   :created_at
    datetime   :updated_at
  end
end
